version: "3.9"
services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postres
      - POSTGRES_PASSWORD=Cluster@1
      - POSTGRES_DB=u_bank
    ports:
      - "5432:5432"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:9090"
    environment:
      - DB_SOURCE=postgresql://postgres:Cluster@1@postgres:5432/u_bank?sslmode=disable
